DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS(
ID INTEGER NOT NULL primary key AUTOINCREMENT,
FIRSTNAME TEXT NOT NULL,
LASTNAME TEXT NOT NULL
);

DROP TABLE IF EXISTS QUIZZES;

CREATE TABLE QUIZZES(
ID INTEGER NOT NULL primary key AUTOINCREMENT,
SUBJECT TEXT,
QUESTION_COUNT INTEGER,
QUIZ_DATE TEXT
);

DROP TABLE IF EXISTS RESULTS;

CREATE TABLE RESULTS(
STUDENTID INTEGER NOT NULL primary key AUTOINCREMENT,
QUIZID INTEGER NOT NULL,
SCORE INTEGER
);